---
title: "Data607_Final_project"
author: "Charls Joseph"
date: "December 5, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}

#install the necessary packages
# install.packages("wordcloud")
# install.packages("tm")
# install.packages("rtweet")
 

library("rtweet")


create_token(
  app = "my_twitter_research_app",
consumer_key <- 'xxxx',
consumer_secret <- 'xxx',
access_token <- 'xxx',
access_secret <- 'xx')

iphone_xs <- search_tweets(
  "#iPhoneXS OR 'iphone XS'", n = 18000, include_rts = FALSE, retryonratelimit = TRUE, lang = 'en'
)

nexus_pxel <- search_tweets(
  "#pixel3 OR pixel3 OR 'Pixel 3'", n = 18000, include_rts = FALSE, retryonratelimit = TRUE, lang = 'en'
)


# iphone_xs_cleaned <- rbind(iphone_xs[1:1600, ], iphone_xs[1700:16500, ])

write_as_csv(x = iphone_xs , file_name = 'iphone_xs.csv')

write_as_csv(x = nexus_pxel , file_name = 'tweets_nexus_pxel.csv')


```

Staging the tweet data into mongoDb 

```{r}


```


Sentimental polarity check

```{r}
require(devtools)
#install_github("sentiment140", "okugami79")
library(sentiment)

nrow(iphone_xs)
sentiments_iphone <- sentiment(iphone_xs$text)
table(sentiments_iphone$polarity)

nrow(nexus_pxel)
sentiments_pixel <- sentiment(nexus_pxel$text)
table(sentiments_pixel$polarity)


```